### PR TITLE
reimport Antora docs component based on latest content from Server (master)

### PR DESCRIPTION
**Pull request by mojavelinux**
- change component name to spark-connector
- change component title to Spark Connector
- shift navigation up a level and add a category
- reimport content
- change start page to index.adoc

### CODE REVIEW

**Comment by mojavelinux** [comment]
@dnault Thanks!

If you'd like me to import the docs for the 2.1 version as well, I just need a branch to target (e.g., release/2.1). Those files would be coming from here: https://github.com/couchbase/docs-cb4/tree/master/content/connectors/spark-2.1

**Comment by dnault** [comment]
Hi @mojavelinux,
Yes, let's plan on importing the 2.1 docs as well. I've requested a `release/2.1` branch, will comment again when it's ready.

**Comment by mojavelinux** [comment]
Thanks @dnault. I'll watch for the notification to come in.

**Comment by dnault** [comment]
Hi @mojavelinux , the `release/2.1` branch is ready.

**Comment by mojavelinux** [comment]
A patch for release/2.1 is now available in gerrit. See http://review.couchbase.org/#/c/99004/

**Pull request closed without merging**
