### PR TITLE
Upgrade to Spark 3.0.0 and introduces working shading of old Java libraries

### PR DESCRIPTION
**Pull request by zzvara**

### CODE REVIEW

**Comment by NathanNZ** [comment]
Looking good! Keen to see this merged in so it can be used with Databricks 7.3 LTS (Scala 2.12 & Spark 3.0.1)

**Comment by programmatix** [comment]
Hi @zzvara .  I just saw this PR, sorry it must have slipped through the cracks.  Thank you for this patchset.  I haven't had a chance to look at it thoroughly yet, but , and this will surely help us with our roadmap goals of porting the Spark Connector to Spark 3.0.0.  (Nb: We have plans to go further and port over to use the Scala SDK as the underlying SDK also.)

**Comment by zzvara** [comment]
Hi @programmatix, porting this to Scala SDK would be very useful, but we noticed that it is large work, so we just shaded the old libraries. Anyway, the SBT model with useful plugins could be quite helpful to you.

This PR works well for us in production.

**Comment by zzvara** [comment]
I will not attempt to rebase this, since AFAIK in 4 months there will be a complete rewrite of this library.

**Pull request closed without merging**
