### PR TITLE
deeply nested attributes are now properly parsed

### PR DESCRIPTION
**Pull request by lucarosellini**
Using deeply nested filter attributes like, for example, EqualTo("root.elem.subelem", 10) leads to the generation of the query string: \`root.elem.subelem\` = 10, which is incorrect. This simple patch allows `N1QLRelation.filterToExpression` to generate the more proper: \`root\`.\`elem\`.\`subelem\` = 10.

### CODE REVIEW

**Comment by daschl** [comment]
@lucarosellini thanks very much! as the bot above explained we do our pull requests through gerrit :)

so the bot has uploaded your change there automatically but you'd need to sign the CLA - can you do that? thanks much!

**Comment by daschl** [comment]
also if you get a chance just rebase http://review.couchbase.org/#/c/64876/ so that its based on current master - but if you just sign the CLA I can do that for you too.

**Comment by daschl** [comment]
@lucarosellini ah and here you go, there should be all the info you need on contributing: https://github.com/couchbase/couchbase-spark-connector/blob/master/CONTRIBUTING.md please ping me if you run into any issues

**Comment by lucarosellini** [comment]
@daschl CLA accepted and PR rebased on current master

**Comment by daschl** [comment]
@lucarosellini hey! I'm sorry maybe I didn't make it clear. All the code changes are handled through gerrit, so the rebasing as well as updating the code and commit messages must be done over gerrit itself, not github issues. (think of it as github is just a mirror of gerrit). 

But if you don't want to do the setup and getting familiar that's fine I can push that in for you. But if you want to contribute in the future it would be great to familiarize, then on the next changeset all the workflow is set :)

**Comment by daschl** [comment]
thanks much for your contribution! I pulled your change in :)

**Comment by lucarosellini** [comment]
@daschl Thank you!

**Comment by daschl** [comment]
1.2.1 released to maven central :)

**Pull request closed without merging**
